---
# RedHat related OSs
- name: Yum install {{ item }}
  yum:
    name: "{{ item }}"
    state: present
  with_items:
  - wget
  - tar
  - gzip
  - java-1.8.0-openjdk
  when: "ansible_os_family == 'RedHat'"

- name: Ubuntu 14 install software-properties-common
  apt:
    name: software-properties-common
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "14"

- name: Ubuntu 14 install OpenJDK PPA repo
  apt_repository:
    repo: 'ppa:openjdk-r/ppa'
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "14"

# Debian related OSs
- name: "Apt install {{ item }}"
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
  - wget
  - tar
  - gzip
  - openjdk-8-jre
  when: "ansible_os_family == 'Debian'"

# download only in the ansible master node
- name: Get hadoop tar.gz
  get_url:
    url: "{{ hadoop_mirrors | random }}/hadoop-{{ hadoop_version }}/hadoop-{{ hadoop_version }}.tar.gz"
    dest: "/tmp/hadoop-{{ hadoop_version }}.tar.gz"
  register: result
  until: result is success
  retries: 5
  delay: 1

- name: Unzip hadoop tar.gz
  unarchive: 
    src: "/tmp/hadoop-{{ hadoop_version }}.tar.gz"
    dest: /opt
    creates: "/opt/hadoop-{{ hadoop_version }}"
    copy: no

- name: Remove hadoop tar.gz
  file:
    path: "/tmp/hadoop-{{ hadoop_version }}.tar.gz"
    state: absent

- name: Link hadoop
  file: 
    dest: "{{ hadoop_home }}"
    src: "/opt/hadoop-{{ hadoop_version }}"
    state: link

- name: Add JAVA_HOME in hadoop ENV
  lineinfile: 
    path: "{{ hadoop_home }}/etc/hadoop/hadoop-env.sh"
    regexp: "export\ JAVA_HOME="
    line: "export JAVA_HOME={{item}}"
  with_first_found:
   - /usr/lib/jvm/java-8-openjdk-amd64
   - /usr/lib/jvm/jre-1.8.0
