# download only in the ansible master node
- local_action: get_url url={{ hadoop_mirrors|random }}/hadoop-{{ hadoop_version }}/hadoop-{{ hadoop_version }}.tar.gz dest="{{ tmp }}/hadoop-{{ hadoop_version }}.tar.gz" force=no
  become: false
  register: result
  until: result is success
  retries: 5
  delay: 2
  when: hadoop_type_of_node == 'master'

# other nodes wait for it
- local_action: wait_for path="{{ tmp }}/hadoop-{{ hadoop_version }}.tar.gz"
  become: false
  when: hadoop_type_of_node != 'master'

- copy: src={{ tmp }}/hadoop-{{ hadoop_version }}.tar.gz dest={{ opt }}/hadoop-{{ hadoop_version }}.tar.gz force=yes

- unarchive: src={{ opt }}/hadoop-{{ hadoop_version }}.tar.gz dest={{ opt }} remote_src=yes

- file: dest={{ hadoop_home }} src={{ opt }}/hadoop-{{ hadoop_version }} state=link

- file: dest={{ opt }}/hadoop src={{ hadoop_home }} state=link

- name: Add hadoop bin dir to system-wide $PATH.
  copy:
    dest: /etc/profile.d/hadoop-path.sh
    content: |
      PATH=$PATH:{{ hadoop_home }}/bin
      export HADOOP_HOME={{ hadoop_home }}

- lineinfile: dest="{{ hadoop_home }}/etc/hadoop/hadoop-env.sh" regexp=JAVA_HOME= line="export JAVA_HOME=/usr/java/default"
