---
- name: Check master keys
  set_fact:
    no_master_keys: false
  when: 
    - master_pub_key is not None
    - master_priv_key is not None

- name: Install hadoop components
  include: install_on_bare_metal.yml

- name: Configure hadoop common components
  include: configure_common.yml

- name: Start hdfs components
  include: service_hdfs.yml
