---
- name: Check master keys
  set_fact:
    master_key: true
  when:
    - master_pub_key != "" or master_priv_key != ""

- name: Check hadoop version
  set_fact:
    hadoop_2: true
  when:
    - hadoop_version.split('.')[0] == "2"

- name: Check httpfs user and password
  fail:
    msg: "You have to specify user and password for httpfs service"
  when:
    - httpfs
    - httpfs_user == None or httpfs_password == None

- name: Install hadoop components
  include: install_on_bare_metal.yml

- name: Install httpfs support tools
  include: install_httpfs_support_tools.yml
  when:
    - httpfs == True
    - hadoop_node_type == 'master'

- name: Configure hadoop common components
  include: configure_common.yml

- name: Start hdfs components
  include: service_hdfs.yml

- name: Start yarn components
  include: service_yarn.yml
  when:
    - yarn == True

- name: Start httpfs components
  include: service_httpfs.yml
  when:
    - httpfs == True
    - hadoop_node_type == 'master'
