---
- name: Check master keys
  set_fact:
    master_key: true
  when: 
    - master_pub_key != "" or master_priv_key != ""

- name: Check hadoop version
  set_fact:
    hadoop_2: true
  when: 
    - hadoop_version.split('.')[0] == "2"

- name: Install hadoop components
  include: install_on_bare_metal.yml

- name: Configure hadoop common components
  include: configure_common.yml

- name: Start hdfs components
  include: service_hdfs.yml

- name: Start yarn components
  include: service_yarn.yml
  when:
    - yarn == True

- name: Start yarn components
  include: service_httpfs.yml
  when:
    - httpfs == True
