---
################################################################################
# Master YARN
################################################################################
- name: Start resourcemanager daemon on master
  command: "{{ hadoop_home }}/bin/yarn --daemon start resourcemanager"
  when:
    - master_key == False
    - not hadoop_2
    - (hadoop_node_type == 'master') or (hadoop_node_type == 'resourcemanager')

- name: "HADOOP 2 @ Start resourcemanager daemon on master"
  command: "{{ hadoop_home }}/sbin/yarn-daemon.sh start resourcemanager"
  when:
    - master_key == False
    - hadoop_2
    - (hadoop_node_type == 'master') or (hadoop_node_type == 'resourcemanager')

################################################################################
# Worker YARN
################################################################################
- name: Start nodemanager daemon on workers
  command: "{{ hadoop_home }}/bin/yarn --daemon start nodemanager"
  when:
    - master_key == False
    - not hadoop_2
    - (hadoop_node_type == 'worker') or (hadoop_node_type == 'nodemanager')

- name: "HADOOP 2 @ Start nodemanager daemon on workers"
  command: "{{ hadoop_home }}/sbin/yarn-daemon.sh start datanode"
  when:
    - master_key == False
    - hadoop_2
    - (hadoop_node_type == 'worker') or (hadoop_node_type == 'datanode')

################################################################################
# Start services from master
################################################################################
##
# YARN
- name: Start globally yarn
  command: "{{ hadoop_home }}/sbin/start-yarn.sh"
  when:
  - master_key == True
  - (hadoop_node_type == 'master') or (hadoop_node_type == 'resourcemanager')
