---
################################################################################
# Master
################################################################################
# CHECK AND STOP HDFS SERVICES
- name: Check namenode daemon on master
  command: "{{ hadoop_home }}/bin/hdfs --daemon status namenode"
  register: namenode_check
  ignore_errors: True
  when:
    - not hadoop_2
    - (hadoop_node_type == 'master') or (hadoop_node_type == 'namenode')

- name: Stop namenode daemon on master
  command: "{{ hadoop_home }}/bin/hdfs --daemon stop namenode"
  register: namenode_stop
  when:
    - not hadoop_2
    - (hadoop_node_type == 'master') or (hadoop_node_type == 'namenode')
    - namenode_check is succeeded

- name: "HADOOP 2 @ Check namenode daemon on master"
  command: "{{ hadoop_home }}/sbin/hadoop-daemon.sh start namenode"
  register: namenode_check
  ignore_errors: True
  when:
    - hadoop_2
    - (hadoop_node_type == 'master') or (hadoop_node_type == 'namenode')

- name: "HADOOP 2 @ Stop namenode daemon on master"
  command: "{{ hadoop_home }}/sbin/hadoop-daemon.sh stop namenode"
  register: namenode_stop
  when:
    - hadoop_2
    - (hadoop_node_type == 'master') or (hadoop_node_type == 'namenode')
    - namenode_check is failed

- name: Check secondarynamenode daemon on master
  command: "{{ hadoop_home }}/bin/hdfs --daemon status secondarynamenode"
  register: secondarynamenode_check
  ignore_errors: True
  when:
    - not hadoop_2
    - (hadoop_node_type == 'master') or (hadoop_node_type == 'secondarynamenode')

- name: Stop secondarynamenode daemon on master
  command: "{{ hadoop_home }}/bin/hdfs --daemon stop secondarynamenode"
  when:
    - not hadoop_2
    - (hadoop_node_type == 'master') or (hadoop_node_type == 'secondarynamenode')
    - secondarynamenode_check is succeeded

- name: "HADOOP 2 @ Check secondarynamenode daemon on master"
  command: "{{ hadoop_home }}/sbin/hadoop-daemon.sh start secondarynamenode"
  register: secondarynamenode_check
  ignore_errors: True
  when:
    - hadoop_2
    - (hadoop_node_type == 'master') or (hadoop_node_type == 'secondarynamenode')

- name: "HADOOP 2 @ Stop secondarynamenode daemon on master"
  command: "{{ hadoop_home }}/sbin/hadoop-daemon.sh stop secondarynamenode"
  when:
    - hadoop_2
    - (hadoop_node_type == 'master') or (hadoop_node_type == 'secondarynamenode')
    - secondarynamenode_check is failed

################################################################################
# CHECK AND STOP YARN SERVICES
- name: Check resourcemanager daemon on master
  command: "{{ hadoop_home }}/bin/yarn --daemon status resourcemanager"
  register: resourcemanager_check
  ignore_errors: True
  when:
    - not hadoop_2
    - (hadoop_node_type == 'master') or (hadoop_node_type == 'resourcemanager')

- name: Stop resourcemanager daemon on master
  command: "{{ hadoop_home }}/bin/yarn --daemon stop resourcemanager"
  when:
    - not hadoop_2
    - (hadoop_node_type == 'master') or (hadoop_node_type == 'resourcemanager')
    - resourcemanager_check is succeeded

- name: "HADOOP 2 @ Check resourcemanager daemon on master"
  command: "{{ hadoop_home }}/sbin/yarn-daemon.sh start resourcemanager"
  register: resourcemanager_check
  ignore_errors: True
  when:
    - hadoop_2
    - (hadoop_node_type == 'master') or (hadoop_node_type == 'resourcemanager')

- name: "HADOOP 2 @ Stop resourcemanager daemon on master"
  command: "{{ hadoop_home }}/sbin/yarn-daemon.sh stop resourcemanager"
  when:
    - hadoop_2
    - (hadoop_node_type == 'master') or (hadoop_node_type == 'resourcemanager')
    - resourcemanager_check is failed