---
################################################################################
# Master HTTPFS
################################################################################
- name: Start httpfs daemon on master
  command: "{{ hadoop_home }}/bin/hdfs --daemon start httpfs"
  when:
    - not hadoop_2

- name: "HADOOP 2 @ Start httpfs daemon on master"
  command: "{{ hadoop_home }}/sbin/httpfs.sh start"
  when:
    - hadoop_2
