# Hadoop 3.x.y

- name: Hadoop 3 restart hadoop-dfs
  shell: "{{ hadoop_home }}/bin/hdfs --daemon stop namenode; {{ hadoop_home }}/bin/hdfs --daemon start namenode"
  when: hadoop_version[0] == '3' and (( hadoop_type_of_node == 'master' ) or ( hadoop_type_of_node == 'namenode' ))
  listen: "restart hadoop-dfs"

- name: Hadoop 3 restart yarn-resourcemanager
  shell: "{{ hadoop_home }}/bin/yarn --daemon stop resourcemanager; {{ hadoop_home }}/bin/yarn --daemon start resourcemanager"
  when: hadoop_version[0] == '3' and (( hadoop_type_of_node == 'master' ) or ( hadoop_type_of_node == 'resourcemanager' ))
  listen: "restart yarn-resourcemanager"

- name: Hadoop 3 restart hadoop-datanode
  shell: "{{ hadoop_home }}/bin/hdfs --daemon stop datanode; {{ hadoop_home }}/bin/hdfs --daemon start datanode"
  when: hadoop_version[0] == '3' and (( hadoop_type_of_node == 'slave' ) or ( hadoop_type_of_node == 'datanode' ))
  listen: "restart hadoop-datanode"
  
- name: Hadoop 3 restart yarn-nodemanager
  shell: "{{ hadoop_home }}/bin/yarn --daemon stop nodemanager; {{ hadoop_home }}/bin/yarn --daemon start nodemanager"
  when: hadoop_version[0] == '3' and (( hadoop_type_of_node == 'slave' ) or ( hadoop_type_of_node == 'nodemanager' ))
  listen: "restart yarn-nodemanager"

# Hadoop 2.x.y
- name: Hadoop 2 restart hadoop-dfs
  shell: "{{ hadoop_home }}/sbin/hadoop-daemon.sh  --script hdfs stop namenode; {{ hadoop_home }}/sbin/hadoop-daemon.sh  --script hdfs start namenode"
  when: hadoop_version[0] == '2' and (( hadoop_type_of_node == 'master' ) or ( hadoop_type_of_node == 'namenode' ))
  listen: "restart hadoop-dfs"
  
- name: Hadoop 2 restart yarn-resourcemanager
  shell: "{{ hadoop_home }}/sbin/yarn-daemon.sh stop resourcemanager; {{ hadoop_home }}/sbin/yarn-daemon.sh start resourcemanager"
  when: hadoop_version[0] == '2' and (( hadoop_type_of_node == 'master' ) or ( hadoop_type_of_node == 'resourcemanager' ))
  listen: "restart yarn-resourcemanager"

- name: Hadoop 2 restart hadoop-datanode
  shell: "{{ hadoop_home }}/sbin/hadoop-daemon.sh  --script hdfs stop datanode; {{ hadoop_home }}/sbin/hadoop-daemon.sh  --script hdfs start datanode"
  when: hadoop_version[0] == '2' and (( hadoop_type_of_node == 'slave' ) or ( hadoop_type_of_node == 'datanode' ))
  listen: "restart hadoop-datanode"
  
- name: Hadoop 2 restart yarn-nodemanager
  shell: "{{ hadoop_home }}/sbin/yarn-daemon.sh stop nodemanager; {{ hadoop_home }}/sbin/yarn-daemon.sh start nodemanager"
  when: hadoop_version[0] == '2' and (( hadoop_type_of_node == 'slave' ) or ( hadoop_type_of_node == 'nodemanager' ))
  listen: "restart yarn-nodemanager"

# Common
- name: refreshDFSNodes
  command: "{{ hadoop_home }}/bin/hdfs dfsadmin -refreshNodes"
  when: ( hadoop_type_of_node == 'master' ) or ( hadoop_type_of_node == 'namenode' )
  ignore_errors: yes
  listen: "refreshDFSNodes"

- name: refreshYarnNodes
  command: "{{ hadoop_home }}/bin/yarn rmadmin -refreshNodes"
  when: ( hadoop_type_of_node == 'master' ) or ( hadoop_type_of_node == 'resourcemanager' )
  ignore_errors: yes
  listen: "refreshYarnNodes"
